version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
        - ./:/usr/src/app
        - nodemodules:/usr/src/app/node_modules
    links:
      - database:database
    depends_on:
      - database
  database:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  nodemodules:
  db:
    driver: local